### ISSUE TITLE
无线端是否支持接收服务端SOCKET消息推送？还是说只能通过嵌入服务商页面来实现？

### ISSUE THREAD

**Issue by colorfullee** [rap-space/rox-package#1]
您好，我是1688服务市场应用开发者，目前在尝试服务端推送消息至无线端，但是贵处文档似乎没有相关说明[文档地址](https://bspace.1688.com/developer/components/mobile/rox-web)，而且文档中提供的[钉钉群二维码](https://img.alicdn.com/tfs/TB1m.DxoFOWBuNjy0FiXXXFxVXa-200-200.png)也是失效的，所以在此想咨询了解下相关解决方案，虽然可以通过接口轮询来使用，但是考虑到用户体验和服务端压力...

**Comment by Lucien-X** [comment]
目前暂不支持接收Socket推送。

入端插件答疑文档，目前维护在语雀上：
https://www.yuque.com/zy7imd/yizt6l/gkdpug

“1688无线入端-ISV技术服务”
钉钉群号是 44566680
入群请备注 公司 - 岗位 - 姓名
二维码容易有过期问题，后续我考虑直接放群号。

**Comment by colorfullee** [comment]
好的，多谢
